### ISSUE TITLE
Latest Config?

### ISSUE THREAD

**Issue by noobydp** [ibash/railcore-klipper#1]
Hey Islam, thanks for sharing this.
I tried to convert my 6hc to klipper last year myself but got frustrated and gave up 😮‍💨.

I'm going to give it another try with your config, but wanted to check if this is the latest + working version?
I know I'll need to change the config for my printer, but figured I'd ask.

Thanks,
DP

**Comment by ibash** [comment]
Good question I'm actually not sure if it's the latest, I'd need to check what's on my printer (which is powered down right now).

I used a fork of klipper for mine that added some nice things for homing, so my latest is probably not usable unless you also wanted to use a fork.

The safest best is probably this version:
https://github.com/ibash/railcore-klipper/blob/16c725df201ce2c3ea41b30ca150b91141d44a70/printer.cfg

With the caveat that you'll want to uncomment "homing_override" and delete "safe_z_home" since that used a fork of klipper.

Other modifications I had on my printer:
* longboi motors on x and y
* euclid probe
* custom air filters (But IIRC that's not in the config)
* an extra cooling fan on the hotend

**Comment by noobydp** [comment]
Woah thats cool, I'll check out your klipper fork as well.

Why the longboi motors?

Did you stop using the pin aliases in that printer.cfg file?
I noticed in https://github.com/ibash/railcore-klipper/blob/main/ibash.cfg you had them.

**Comment by ibash** [comment]
Live in an apartment and they're quieter :)
Yeah I stopped using the aliases, I think because I I never finished a printer.cfg with aliases, and instead restarted based on someone else's config.

**Comment by noobydp** [comment]
Nice I might give the motors a try too, mine is pretty noisy compared to my old anet a6. 
After a ton of upgrades to the anet, it could be printing behind me and I'd forget its running :O

Then I built the voron and had to move it into a separate room 🤦

**Comment by noobydp** [comment]
Hey, I managed to get up and running thanks to your help.
I changed a ton of stuff but your config was a really good starting point.

I have 1 question: you have sense_resistor: 0.05, but I thought it was supposed to be 0.075, do you remember why?

**Comment by ibash** [comment]
So I think this is based off the schematic here: https://github.com/Duet3D/Duet3-Mainboard-6HC/blob/master/Duet3_Mainboard_6HC_v1.01/Duet3_MB_Schematic_v1.01.pdf

If you look at the drivers SRBH/SRBL and SRAH/SRHL connect to the sense resistor. At least for my model of duet3 (would double check your own) it says "0R05" (on the far right). I _think_ that's the value to use:

<img width="720" alt="Screenshot 2023-05-09 at 10 54 56 AM" src="https://github.com/ibash/railcore-klipper/assets/204566/a022e9a1-6a92-47e9-aebe-eadd6bf7d10e">

-

Also the tmc datasheet is useful and I think backs it up, although there's capacitors/resistors for filtering, it's just the far right resistor value that matters (this is the diagram under "standard application circuit"): https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC5160A_Datasheet_Rev1.14.pdf

<img width="332" alt="Screenshot 2023-05-09 at 10 57 30 AM" src="https://github.com/ibash/railcore-klipper/assets/204566/a02a17d4-7823-44f9-ba7d-fb1818c19bc3">

(My model of duet3 uses the 2160, but think they're roughly equivalent.)

**Comment by ibash** [comment]
I know there were differences between the duet3 versions, so would check the schematic for your board specifically.

**Comment by noobydp** [comment]
That’s great thanks. I got the 75 from duet forums and other examples for the 5160 but I think they’re wrong. Luckily I noticed my motors were burning hot during a short print, also explains the increase in noise I heard in kilo compared with duet firmware. On 10 May 2023, at 2:00 am, Islam Sharabash ***@***.***> wrote:﻿
I know there were differences between the duet3 versions, so would check the schematic for your board specifically.
